server:
  port: 8080

spring:
  datasource:
    username: root
    password: wenqi123
    url: jdbc:mysql://localhost:3306/activiti?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  application:
    name: activity-work

  #activity
  activiti:
    #设置为不校验/resources/processes下的流程文件，这样就不会报错
    check-process-definitions: false
    #设置为该值后，Activiti会对数据库中所有的表进行更新，如果表不存在，则Activiti会自动创建。
    database-schema-update: true
    #保存历史数据级别设置为full最高级别，便于历史数据的追溯
    history-level: full

